apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
    name: pipeline-buildpush
spec:
  pipelineRef:
    name: pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi