apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---     
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "wordsec"
            - name: MYSQL_DATABASE
              value: "DataBaseMon"
            - name: MYSQL_USER
              value: "MyWordPress"
            - name: MYSQL_PASSWORD
              value: "wordsec"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      # restartPolicy: OnFailure
      # initContainers:
      #   - name: init
      #     image: dmonakh/init_db_wp:v1
      #     env:
      #       - name: SERVER_NAME
      #         value: "mysql"
      #       - name: USER_NAME
      #         value: "root"
      #       - name: PASSWORD
      #         value: "wordsec"
      #     volumeMounts:
      #       - name: wordpress-persistent-storage
      #         mountPath: /var/www/html
      #       - name: mysql-persistent-storage
      #         mountPath: /var/lib/mysql
      # initContainers:
      #   - name: init
      #     image: wordpress:cli
      #     env:
      #       - name: SERVER_NAME
      #         value: "mysql"
      #       - name: USER_NAME
      #         value: "root"
      #       - name: PASSWORD
      #         value: "wordsec"
      #     volumeMounts:
      #       - name: wordpress-persistent-storage
      #         mountPath: /var/www/html
      #       - name: mysql-persistent-storage
      #         mountPath: /var/lib/mysql
      #     command: ["/bin/sh", "-c"]
      #     args:
      #       - /scripts/init_cli.sh
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql"
            - name: WORDPRESS_DB_NAME
              value: "DataBaseMon"
            - name: WORDPRESS_DB_USER
              value: "MyWordPress"
            - name: WORDPRESS_DB_PASSWORD
              value: "wordsec"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
