name: Terraform deploy kubernetes cluster

on:
  push:
    paths:
      - 'terraform_gcp/**'
      - '.github/workflows/Wehooks.yml'
    branches:
      - main
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs: 
  Webhooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform_gcp

    steps:
    - name: Clon Rep
      uses: actions/checkout@v3  

    - name: Decode credentials
      run: echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > credentials_file.json

    - name: Authenticate with Google Cloud
      run: |
        gcloud config set account ${SA_NAME}
        gcloud auth activate-service-account --key-file=credentials_file.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Auth Plugin for cluster
      uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - name: Get kubeconfig 
      run: gcloud container clusters get-credentials $CLUSTER_NAME --region=$REGION --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Получение внешнего IP-адреса
      id: get-external-ip
      run: |
        external_ip=$(kubectl get service -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "External IP: $external_ip"

    - name: Add webhook
      env:
        SCRIPT_DIR: ${{ github.workspace }}/terraform_gcp/scripts
      run: |
        external_ip=${{ steps.get-external-ip.outputs.external-ip }}
        bash  $SCRIPT_DIR/add-webhook.sh