name: Terraform deploy kubernetes cluster

on:
  push:
    paths:
      - 'terraform_gcp/**'
      - '.github/workflows/Wehooks.yml'
    branches:
      - main
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs: 
  Webhooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform_gcp

    steps:
    - name: Clon Rep
      uses: actions/checkout@v3  

    - name: Получение внешнего IP-адреса
      id: get-external-ip
      run: |
        external_ip=$(kubectl get service -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "External IP: $external_ip"

    - name: Add webhook
      env:
        SCRIPT_DIR: ${{ github.workspace }}/terraform_gcp/scripts
      run: |
        external_ip=${{ steps.get-external-ip.outputs.external-ip }}
        bash  $SCRIPT_DIR/add-webhook.sh