name: Terraform deploy kubernetes cluster

on:
  push:
    paths:
      - 'terraform_gcp/**'
      - '.github/workflows/Wehooks.yml'
    branches:
      - main
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BUCKET_NAME: mondybucketgcp
  SA_NAME: git-490@tidy-vent-384809.iam.gserviceaccount.com 
  CLUSTER_NAME: mondyspout-clusterk8s
  REGION: us-central1

jobs: 
  Webhooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform_gcp

    steps:
    - name: Clon Rep
      uses: actions/checkout@v3  

    - name: Decode credentials
      run: echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > credentials_file.json

    - name: Authenticate with Google Cloud
      run: |
        gcloud config set account ${SA_NAME}
        gcloud auth activate-service-account --key-file=credentials_file.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Auth Plugin for cluster
      uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - name: Get kubeconfig 
      run: gcloud container clusters get-credentials $CLUSTER_NAME --region=$REGION --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Get NGINX External IP
      env:
        SCRIPT_DIR: ${{ github.workspace }}/terraform_gcp/scripts
      run: |
        external_ip=$(kubectl describe service -n ingress-nginx | grep "LoadBalancer Ingress:" | awk '{print $3}')
        echo "External IP: $external_ip"
        bash $SCRIPT_DIR/add-webhook.sh $external_ip

    - name: Add webhook
      run: |
        echo "External IP: ${{ steps.get-external-ip.outputs.external_ip }}"
      # env:
      #   SCRIPT_DIR: ${{ github.workspace }}/terraform_gcp/scripts
      # run: |
      #   external_ip=${{ steps.get-external-ip.outputs.external_ip }}
      #   echo "External IP: $external_ip"
      #   bash $SCRIPT_DIR/add-webhook.sh $external_ip
